name: HELLO WORLD 

on: [push, pull_request]


jobs:

  anything:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: failed

  nothing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo "GOODBYE"

